# Generated by Django 5.2 on 2025-04-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0004_auto_20250411_1315'),
        ('workflows', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='script',
            name='workflows',
            field=models.ManyToManyField(blank=True, related_name='related_scripts', to='workflows.workflow'),
        ),
    ]
