# Generated by Django 5.2 on 2025-04-11 00:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('core', 'Core System'), ('integration', 'Integration'), ('custom', 'Custom Component'), ('external', 'External System')], max_length=50)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('support_information', models.TextField(blank=True)),
                ('contact_information', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_structure', models.CharField(blank=True, max_length=255)),
                ('sso_methodology', models.CharField(blank=True, max_length=255)),
                ('sso_system', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('active', 'Going-Concern'), ('review', 'In Review'), ('deprecation', 'Scheduled for Deprecation'), ('deprecated', 'Deprecated')], default='active', max_length=20)),
                ('documentation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='SystemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='system_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='systems.system')),
            ],
        ),
        migrations.CreateModel(
            name='SystemRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('depends_on', 'Depends On'), ('provides_data_to', 'Provides Data To'), ('integrates_with', 'Integrates With')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='systems.system')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='systems.system')),
            ],
            options={
                'unique_together': {('source_system', 'target_system', 'relationship_type')},
            },
        ),
    ]
