# Generated by Django 5.2 on 2025-04-11 14:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#f2f2f2', help_text='CSS color code (e.g., #3498db)', max_length=20)),
                ('text_color', models.CharField(default='#333333', help_text='Text color (e.g., #333333)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g., fa-server)', max_length=50)),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'System Category',
                'verbose_name_plural': 'System Categories',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='SystemStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
                ('color', models.CharField(default='#f2f2f2', help_text='CSS color code (e.g., #3498db)', max_length=20)),
                ('text_color', models.CharField(default='#333333', help_text='Text color (e.g., #333333)', max_length=20)),
                ('icon', models.CharField(blank=True, help_text='CSS class for icon (e.g., fa-check)', max_length=50)),
                ('is_active', models.BooleanField(default=True, help_text='Whether systems with this status are considered active')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order')),
            ],
            options={
                'verbose_name': 'System Status',
                'verbose_name_plural': 'System Statuses',
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='System',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('vendor', models.CharField(blank=True, max_length=255)),
                ('operating_system', models.CharField(blank=True, max_length=100)),
                ('support_information', models.TextField(blank=True)),
                ('contact_information', models.TextField(blank=True)),
                ('cost', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('cost_structure', models.CharField(blank=True, max_length=255)),
                ('documentation_url', models.URLField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hosting_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hosted_systems', to='systems.system')),
                ('sso_system', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_dependent_systems', to='systems.system')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='systems.systemcategory')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='systems', to='systems.systemstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SystemDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('document', models.FileField(upload_to='system_documents/')),
                ('description', models.TextField(blank=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='systems.system')),
            ],
        ),
        migrations.CreateModel(
            name='SystemNote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_notes', to=settings.AUTH_USER_MODEL)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notes', to='systems.system')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SystemAdministrator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_primary', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administrators', to='systems.system')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='administered_systems', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('system', 'user')},
            },
        ),
        migrations.CreateModel(
            name='SystemRelationship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relationship_type', models.CharField(choices=[('depends_on', 'Depends On'), ('provides_data_to', 'Provides Data To'), ('integrates_with', 'Integrates With')], max_length=50)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('source_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outgoing_relationships', to='systems.system')),
                ('target_system', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='incoming_relationships', to='systems.system')),
            ],
            options={
                'unique_together': {('source_system', 'target_system', 'relationship_type')},
            },
        ),
    ]
