# Generated by Django 5.2 on 2025-04-11 19:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scripts', '0005_alter_script_workflows'),
        ('workflows', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='workflow',
            name='edges',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflow',
            name='nodes',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='workflow',
            name='scripts',
            field=models.ManyToManyField(blank=True, related_name='used_in_workflows', to='scripts.script'),
        ),
        migrations.AddField(
            model_name='workflow',
            name='version',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.CreateModel(
            name='WorkflowVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField()),
                ('nodes', models.JSONField(blank=True, default=dict)),
                ('edges', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('workflow', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='workflows.workflow')),
            ],
            options={
                'ordering': ['-version'],
                'unique_together': {('workflow', 'version')},
            },
        ),
        migrations.DeleteModel(
            name='WorkflowStep',
        ),
    ]
